--
-- PostgreSQL database dump
--

\restrict swQ750hiU33oD8WYKgyomnKUjfe7gcZ2KpLM0T5gGB7SI5TXbByA88beZzegnXq

-- Dumped from database version 16.11 (Ubuntu 16.11-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 17.7 (Ubuntu 17.7-3.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categorias_habitacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categorias_habitacion (
    id_categoria integer NOT NULL,
    descripcion text,
    nombre character varying(50) NOT NULL,
    usuario_id integer
);


ALTER TABLE public.categorias_habitacion OWNER TO postgres;

--
-- Name: categorias_habitacion_id_categoria_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categorias_habitacion ALTER COLUMN id_categoria ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categorias_habitacion_id_categoria_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ciudades; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ciudades (
    id_ciudad integer NOT NULL,
    created_at timestamp(6) without time zone,
    latitud numeric(10,8),
    longitud numeric(11,8),
    nombre character varying(100) NOT NULL,
    id_departamento integer NOT NULL
);


ALTER TABLE public.ciudades OWNER TO postgres;

--
-- Name: ciudades_id_ciudad_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ciudades ALTER COLUMN id_ciudad ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ciudades_id_ciudad_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: departamentos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.departamentos (
    id_departamento integer NOT NULL,
    created_at timestamp(6) without time zone,
    nombre character varying(100) NOT NULL
);


ALTER TABLE public.departamentos OWNER TO postgres;

--
-- Name: departamentos_id_departamento_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.departamentos ALTER COLUMN id_departamento ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.departamentos_id_departamento_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: habitaciones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.habitaciones (
    id_habitacion integer NOT NULL,
    capacidad integer NOT NULL,
    created_at timestamp(6) without time zone,
    descripcion text,
    estado character varying(255) NOT NULL,
    numero character varying(20) NOT NULL,
    precio double precision NOT NULL,
    updated_at timestamp(6) without time zone,
    id_categoria integer,
    id_hotel integer NOT NULL,
    CONSTRAINT habitaciones_estado_check CHECK (((estado)::text = ANY ((ARRAY['disponible'::character varying, 'mantenimiento'::character varying])::text[])))
);


ALTER TABLE public.habitaciones OWNER TO postgres;

--
-- Name: habitaciones_id_habitacion_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.habitaciones ALTER COLUMN id_habitacion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.habitaciones_id_habitacion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hoteles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.hoteles (
    id_hotel integer NOT NULL,
    check_in time(6) without time zone,
    check_out time(6) without time zone,
    created_at timestamp(6) without time zone,
    descripcion text,
    direccion character varying(200) NOT NULL,
    email character varying(100),
    estrellas integer DEFAULT 3,
    imagen_url character varying(500),
    nombre character varying(150) NOT NULL,
    politica_cancelacion text,
    telefono character varying(50),
    updated_at timestamp(6) without time zone,
    id_ciudad integer NOT NULL,
    id_usuario integer NOT NULL
);


ALTER TABLE public.hoteles OWNER TO postgres;

--
-- Name: hoteles_id_hotel_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.hoteles ALTER COLUMN id_hotel ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hoteles_id_hotel_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: imagenes_habitacion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.imagenes_habitacion (
    id_imagen integer NOT NULL,
    url_imagen character varying(255) NOT NULL,
    id_habitacion integer NOT NULL
);


ALTER TABLE public.imagenes_habitacion OWNER TO postgres;

--
-- Name: imagenes_habitacion_id_imagen_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.imagenes_habitacion ALTER COLUMN id_imagen ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.imagenes_habitacion_id_imagen_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pagos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pagos (
    id_pago integer NOT NULL,
    fecha_pago timestamp(6) without time zone,
    metodo character varying(255) NOT NULL,
    monto double precision NOT NULL,
    referencia_pago character varying(100),
    id_reserva integer NOT NULL,
    CONSTRAINT pagos_metodo_check CHECK (((metodo)::text = ANY ((ARRAY['tarjeta'::character varying, 'efectivo'::character varying, 'transferencia'::character varying, 'nequi'::character varying, 'daviplata'::character varying])::text[])))
);


ALTER TABLE public.pagos OWNER TO postgres;

--
-- Name: pagos_id_pago_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pagos ALTER COLUMN id_pago ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pagos_id_pago_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resenas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.resenas (
    id_resena integer NOT NULL,
    calificacion integer NOT NULL,
    comentario text,
    fecha_resena character varying(255),
    id_hotel integer NOT NULL,
    id_usuario integer NOT NULL
);


ALTER TABLE public.resenas OWNER TO postgres;

--
-- Name: resenas_id_resena_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.resenas ALTER COLUMN id_resena ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resenas_id_resena_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reservas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reservas (
    id_reserva integer NOT NULL,
    estado character varying(255) NOT NULL,
    fecha_fin date NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_reserva timestamp(6) without time zone,
    metodo_pago character varying(255) NOT NULL,
    total double precision NOT NULL,
    id_habitacion integer NOT NULL,
    id_usuario integer NOT NULL,
    CONSTRAINT reservas_estado_check CHECK (((estado)::text = ANY ((ARRAY['pendiente'::character varying, 'confirmada'::character varying, 'cancelada'::character varying])::text[]))),
    CONSTRAINT reservas_metodo_pago_check CHECK (((metodo_pago)::text = ANY ((ARRAY['tarjeta'::character varying, 'efectivo'::character varying, 'transferencia'::character varying, 'nequi'::character varying, 'daviplata'::character varying])::text[])))
);


ALTER TABLE public.reservas OWNER TO postgres;

--
-- Name: reservas_id_reserva_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reservas ALTER COLUMN id_reserva ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reservas_id_reserva_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario_roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario_roles (
    usuario_id integer NOT NULL,
    rol_id bigint NOT NULL
);


ALTER TABLE public.usuario_roles OWNER TO postgres;

--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    id_usuario integer NOT NULL,
    contrasena character varying(255) NOT NULL,
    documento character varying(255),
    email character varying(255) NOT NULL,
    estado boolean NOT NULL,
    fecha_registro timestamp(6) without time zone,
    foto_url character varying(255),
    nombre_completo character varying(255) NOT NULL,
    telefono character varying(255)
);


ALTER TABLE public.usuarios OWNER TO postgres;

--
-- Name: usuarios_id_usuario_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuarios ALTER COLUMN id_usuario ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_usuario_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categorias_habitacion categorias_habitacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categorias_habitacion
    ADD CONSTRAINT categorias_habitacion_pkey PRIMARY KEY (id_categoria);


--
-- Name: ciudades ciudades_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ciudades
    ADD CONSTRAINT ciudades_pkey PRIMARY KEY (id_ciudad);


--
-- Name: departamentos departamentos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departamentos
    ADD CONSTRAINT departamentos_pkey PRIMARY KEY (id_departamento);


--
-- Name: habitaciones habitaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.habitaciones
    ADD CONSTRAINT habitaciones_pkey PRIMARY KEY (id_habitacion);


--
-- Name: hoteles hoteles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hoteles
    ADD CONSTRAINT hoteles_pkey PRIMARY KEY (id_hotel);


--
-- Name: imagenes_habitacion imagenes_habitacion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.imagenes_habitacion
    ADD CONSTRAINT imagenes_habitacion_pkey PRIMARY KEY (id_imagen);


--
-- Name: pagos pagos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT pagos_pkey PRIMARY KEY (id_pago);


--
-- Name: resenas resenas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.resenas
    ADD CONSTRAINT resenas_pkey PRIMARY KEY (id_resena);


--
-- Name: reservas reservas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservas
    ADD CONSTRAINT reservas_pkey PRIMARY KEY (id_reserva);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: departamentos uk9vfgma390a16fkev3ryhnyrvh; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.departamentos
    ADD CONSTRAINT uk9vfgma390a16fkev3ryhnyrvh UNIQUE (nombre);


--
-- Name: usuarios ukkfsp0s1tflm1cwlj8idhqsad0; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT ukkfsp0s1tflm1cwlj8idhqsad0 UNIQUE (email);


--
-- Name: categorias_habitacion ukl32mevm8ewtlh4csl7fpg5pt3; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categorias_habitacion
    ADD CONSTRAINT ukl32mevm8ewtlh4csl7fpg5pt3 UNIQUE (nombre);


--
-- Name: roles ukofx66keruapi6vyqpv6f2or37; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);


--
-- Name: usuario_roles usuario_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_roles
    ADD CONSTRAINT usuario_roles_pkey PRIMARY KEY (usuario_id, rol_id);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id_usuario);


--
-- Name: resenas fk1bf3epj4o04bhsp17nlokbl8k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.resenas
    ADD CONSTRAINT fk1bf3epj4o04bhsp17nlokbl8k FOREIGN KEY (id_hotel) REFERENCES public.hoteles(id_hotel);


--
-- Name: reservas fk82xsvc8wvp8d5sf73ocjoeqab; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservas
    ADD CONSTRAINT fk82xsvc8wvp8d5sf73ocjoeqab FOREIGN KEY (id_habitacion) REFERENCES public.habitaciones(id_habitacion);


--
-- Name: pagos fk8y8c5vtchywg1hc0so39gg56j; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT fk8y8c5vtchywg1hc0so39gg56j FOREIGN KEY (id_reserva) REFERENCES public.reservas(id_reserva);


--
-- Name: ciudades fk_ciudad_departamento; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ciudades
    ADD CONSTRAINT fk_ciudad_departamento FOREIGN KEY (id_departamento) REFERENCES public.departamentos(id_departamento);


--
-- Name: hoteles fk_hotel_ciudad; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hoteles
    ADD CONSTRAINT fk_hotel_ciudad FOREIGN KEY (id_ciudad) REFERENCES public.ciudades(id_ciudad);


--
-- Name: hoteles fk_hotel_usuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.hoteles
    ADD CONSTRAINT fk_hotel_usuario FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario);


--
-- Name: usuario_roles fkbt9i9yrb9ug88xnh82n9m60pr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_roles
    ADD CONSTRAINT fkbt9i9yrb9ug88xnh82n9m60pr FOREIGN KEY (rol_id) REFERENCES public.roles(id);


--
-- Name: habitaciones fkdt09g936qaeh78qp1130b8qnk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.habitaciones
    ADD CONSTRAINT fkdt09g936qaeh78qp1130b8qnk FOREIGN KEY (id_hotel) REFERENCES public.hoteles(id_hotel);


--
-- Name: categorias_habitacion fkfght038l8o3y7e12qri9a1e2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categorias_habitacion
    ADD CONSTRAINT fkfght038l8o3y7e12qri9a1e2 FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id_usuario);


--
-- Name: reservas fkhjryje6u1cr0d4dubad1jja6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reservas
    ADD CONSTRAINT fkhjryje6u1cr0d4dubad1jja6 FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario);


--
-- Name: habitaciones fkpv6vsplxxhv7ajgyjo2bkpvaw; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.habitaciones
    ADD CONSTRAINT fkpv6vsplxxhv7ajgyjo2bkpvaw FOREIGN KEY (id_categoria) REFERENCES public.categorias_habitacion(id_categoria);


--
-- Name: imagenes_habitacion fkq7kncxii43xp4xu0tqcgagi7o; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.imagenes_habitacion
    ADD CONSTRAINT fkq7kncxii43xp4xu0tqcgagi7o FOREIGN KEY (id_habitacion) REFERENCES public.habitaciones(id_habitacion);


--
-- Name: resenas fkqaeivr368abuesw1nin0scdr4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.resenas
    ADD CONSTRAINT fkqaeivr368abuesw1nin0scdr4 FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id_usuario);


--
-- Name: usuario_roles fkuu9tea04xb29m2km5lwe46ua; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario_roles
    ADD CONSTRAINT fkuu9tea04xb29m2km5lwe46ua FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id_usuario);


--
-- PostgreSQL database dump complete
--

\unrestrict swQ750hiU33oD8WYKgyomnKUjfe7gcZ2KpLM0T5gGB7SI5TXbByA88beZzegnXq

